### ISSUE TITLE
IOError: Failed to interpret file 'IAN_simple.npz' as a pickle

### ISSUE THREAD

**Issue by Elijas** [ajbrock/Neural-Photo-Editor#15]
> 
Traceback (most recent call last):
  File ".\NPE.py", line 18, in <module>
    model = IAN(config_path = 'IAN_simple.py', dnn = False)
  File "C:\Users\user\Desktop\Neural-Photo-Editor-master\API.py", line 30, in __init__
    GANcheckpoints.load_weights(self.weights_fname,params)
  File "C:\Users\user\Desktop\Neural-Photo-Editor-master\GANcheckpoints.py", line 39, in load_weights
    param_dict = np.load(fname)
  File "C:\Python27\lib\site-packages\numpy\lib\npyio.py", line 429, in load
    "Failed to interpret file %s as a pickle" % repr(file))
IOError: Failed to interpret file 'IAN_simple.npz' as a pickle
> 

Any ideas?

**Comment by ajbrock** [comment]
This is an error relating to my naive usage of GIT-LFS. Download the file from [this Drive mirror](https://drive.google.com/open?id=0B3_iVBZsC4GGck5WWWc0R0dvT1U)
